const productsList = [
	{
		id_product: 1,
		category: 'sal',
		fk_idcategories: 1,
		name_product: 'Reeflowers Caledonia Coral Salt 22,5 Kg',
		price: 757.4,
		image: './images/produtos/reeflowers-caledonia_coral_salt_22.5kg.webp',
		id_categories: 1,
		name_categories: 'Sal Marinho Natural',
		selected: false,
	},
	{
		id_product: 2,
		category: 'microelementos',
		fk_idcategories: 1,
		name_product: 'Brightweel Neophos',
		price: 149.9,
		image: './images/produtos/brightwell-neophos.webp',
		id_categories: 1,
		name_categories: 'Microelementos',
		selected: false,
	},
	{
		id_product: 9,
		category: 'testes',
		fk_idcategories: 1,
		name_product: 'Aquaforest Nitrate Test Pro',
		price: 119.9,
		image: './images/produtos/aquaforest-teste-nitrato.webp',
		id_categories: 1,
		name_categories: 'Testes',
		selected: false,
	},
	{
		id_product: 4,
		category: 'alimento-corais',
		fk_idcategories: 1,
		name_product: 'SEACHEM Phyto Plankton 250 ml',
		price: 89,
		image: './images/produtos/seachem-phyto-plankton-250ml.webp',
		id_categories: 1,
		name_categories: 'Alimento Corais',
		selected: false,
	},
	{
		id_product: 10,
		category: 'alimento-peixes',
		fk_idcategories: 1,
		name_product: 'Tropical Super Spirulina Forte 50g',
		price: 99,
		image: './images/produtos/Tropical-Spirulina-50g.webp',
		id_categories: 1,
		name_categories: 'Alimento Peixes',
		selected: false,
	},
	{
		id_product: 11,
		category: 'bombas',
		fk_idcategories: 1,
		name_product: 'Nyos Viper 2.0',
		price: 900,
		image: './images/produtos/nyos-viper-2.webp',
		id_categories: 1,
		name_categories: 'Bombas',
		selected: false,
	},
	{
		id_product: 6,
		category: 'testes',
		fk_idcategories: 2,
		name_product: 'Aquaforest Calcium Test Pro',
		price: 188.5,
		image: './images/produtos/aquaforest-test-pro-ca-1.webp',
		id_categories: 2,
		name_categories: 'Testes',
		selected: false,
	},
	{
		id_product: 7,
		category: 'alimento-peixes',
		fk_idcategories: 2,
		name_product: 'Poytara Black Line Immunity 35g',
		price: 26,
		image: './images/produtos/PoytaraBlacklineImmunity600.webp',
		id_categories: 2,
		name_categories: 'Alimento Peixes',
		selected: false,
	},
	{
		id_product: 3,
		category: 'alimento-peixes',
		fk_idcategories: 3,
		name_product: 'Poytara Spirulina Black Line Pellets M 45g',
		price: 35,
		image: './images/produtos/poytara-black-line-spirulina-1-1.webp',
		id_categories: 3,
		name_categories: 'Alimento Peixes',
		selected: false,
	},
	{
		id_product: 5,
		category: 'sal',
		fk_idcategories: 2,
		name_product: 'Aquaforest Reef Salt – 2 kg',
		price: 121.88,
		image: './images/produtos/sal-aquaforest-reef-salt-2kg.webp',
		id_categories: 2,
		name_categories: 'Sal Marinho Sintético',
		selected: false,
	},
];

export default productsList;
